apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: exp
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: dGVzdEBnbWFpbC5jb20= # test@gmail.com  # base64-encoded
  PGADMIN_DEFAULT_PASSWORD: dGVzdA==  # test # base64-encoded
