apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4        
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: configmap
          volumeMounts:
            - mountPath: "/var/lib/pgadmin"
              name: pgadmin-storage
      volumes:
        - name: pgadmin-storage
          emptyDir: {}  # Use PersistentVolumeClaim for persistent storage
