apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: exp
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/alija/postgres-data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: postgres-storage
