apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: exp
data:
  PSQL_NAME: "devops_db" # database
  PSQL_SERVICE: "postgres-service"
  PSQL_PORT: "5432"

  POSTGRES_DB: "devops_db"
  POSTGRES_HOST: "postgres-service"

  VITE_API_URL: "http://api.exptrackapp.local/api"