apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: exp
data:
  POSTGRES_USER: dGVzdHVzZXI=   # base64-encoded
  POSTGRES_PASSWORD: dGVzdHVzZXI=   # base64-encoded
  PGADMIN_DEFAULT_EMAIL: dGVzdEBnbWFpbC5jb20=   # base64-encoded
  PGADMIN_DEFAULT_PASSWORD: dGVzdA==   # base64-encoded

  PSQL_USER: dGVzdHVzZXI=
  PSQL_PASSWORD: dGVzdHVzZXI=