apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.backend.appLabel }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}