apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configMapRef }}

  namespace: {{ .Release.Namespace }}
data:
  PSQL_NAME: "{{ .Values.backend.config.psqlName }}"
  PSQL_SERVICE: "{{ .Values.backend.config.psqlService }}"
  PSQL_PORT: "{{ .Values.backend.config.psqlPort }}"

  settings.py: |-
{{ .Files.Get "backend/settings.py" | indent 4 }}
