apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretRef }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  PSQL_USER: {{ .Values.backend.secret.psqlUser | b64enc }}
  PSQL_PASSWORD: {{ .Values.backend.secret.psqlPassword | b64enc }}
