apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvc.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
