apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.pv.volumeName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.postgres.pvc.storage }}
  hostPath:
    path: {{ .Values.postgres.pv.path }}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
