apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: "{{ .Values.postgres.secret.POSTGRES_USER | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.secret.POSTGRES_PASSWORD | b64enc }}"
